language: go
sudo: required
go:
    - 1.4
    - 1.5
os:
    - linux
    - osx
env:
 - XML2RFC_VERSION=2.5.0
 - XML2RFC_VERSION=2.4.12
# let the osx builds fail for a while
matrix:
  allow_failures:
    os:
      - osx
# get our python environment up and running
addons:
  apt:
    packages:
    - python
    - python-dev
# bring in xml2rfc and bats for testing
before_install:
    - sudo pip install xml2rfc==$XML2RFC_VERSION
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python-software-properties ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:duggan/bats ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install bats ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bats; fi
install:
    - go get -d -t -v ./...
    - go build -v ./...
script:
    - go test -v ./...
    - xml2rfc -V
    - bats -v
    - cd "$TRAVIS_BUILD_DIR"     && make
    - cd "$TRAVIS_BUILD_DIR"/rfc && make all
