language: go
sudo: required
go:
    - 1.4
    - 1.5
os:
    - linux
    - osx
env:
 - XML2RFC_VERSION=2.5.0
 - XML2RFC_VERSION=2.5.1.dev0
 - XML2RFC_VERSION=2.4.12
# let the osx builds fail for a while
matrix:
  allow_failures:
    os:
      - osx
# get our python environment up and running
addons:
  apt:
    packages:
    - python
    - python-dev
before_install:
    - sudo pip install xml2rfc==$XML2RFC_VERSION
install:
    - go get -d -t -v ./...
    - go build -v ./...
script:
    - go test -v ./...
    - xml2rfc -V
